# Generated by Django 5.2.4 on 2025-07-10 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cafe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('precio', models.FloatField()),
                ('cantidad', models.IntegerField()),
                ('imagen_red', models.CharField(max_length=2999)),
            ],
        ),
    ]
